server:
  port: 8080
  servlet:
    context-path: /flightapp
    session:
      timeout: 15m
amadeus:
  api:
    key: EP4hJKUuuui7lU4HcP2om1e1I98h2ACB
    secret: A7mdRWTdegNiDI98
    environment: test

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flightapp
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    converters:
      preferred-json-mapper: gson
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG